import { BadRequestException, Injectable, NotFoundException } from "@nestjs/common";
import type { APIKey, APIKeyScope } from "@prisma/client";
import { PrismaService } from "../prisma/prisma.service";
import { AuditService } from "../audit/audit.service";
import type { RequestMeta } from "../common/utils/request-meta.util";
import { generateApiKey } from "../common/utils/api-key.util";
import type { CreateApiKeyDto } from "./dto/create-api-key.dto";
import type { RotateApiKeyDto } from "./dto/rotate-api-key.dto";

type ApiKeyWithScopes = APIKey & { scopes: APIKeyScope[] };

/**
 * CRUD/lifecycle around APIKey. `keyHash` is the only persisted secret
 * material (SHA-256 of the plaintext, generated by generateApiKey) - it is
 * stripped from every return value here except the moment of creation/
 * rotation, where the freshly-generated plaintext is attached exactly once
 * so the caller can display/copy it. It is never stored anywhere and never
 * recoverable after this response.
 */
@Injectable()
export class ApiKeysService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly auditService: AuditService,
  ) {}

  async create(apiClientId: string, dto: CreateApiKeyDto, userId: string, meta: RequestMeta) {
    const client = await this.prisma.aPIClient.findUniqueOrThrow({ where: { id: apiClientId } });
    const generated = generateApiKey(dto.environment ?? "live");

    const apiKey = await this.prisma.aPIKey.create({
      data: {
        apiClientId,
        name: dto.name,
        keyPrefix: generated.keyPrefix,
        keyHash: generated.keyHash,
        lastFour: generated.lastFour,
        rateLimitPerMin: dto.rateLimitPerMin,
        expiresAt: dto.expiresAt ? new Date(dto.expiresAt) : undefined,
        scopes: dto.scopes?.length ? { create: dto.scopes.map((scope) => ({ scope })) } : undefined,
      },
      include: { scopes: true },
    });

    await this.auditService.record({
      action: "API_KEY_CREATED",
      userId,
      organizationId: client.organizationId,
      applicationId: client.applicationId ?? undefined,
      metadata: { apiKeyId: apiKey.id, apiClientId, name: apiKey.name },
      ...meta,
    });

    return { ...this.toSafeKey(apiKey), plainText: generated.plainText };
  }

  async list(apiClientId: string) {
    const keys = await this.prisma.aPIKey.findMany({
      where: { apiClientId },
      include: { scopes: true },
      orderBy: { createdAt: "desc" },
    });
    return keys.map((key) => this.toSafeKey(key));
  }

  async getOne(apiClientId: string, apiKeyId: string) {
    const key = await this.getOwnedKey(apiClientId, apiKeyId);
    return this.toSafeKey(key);
  }

  async revoke(apiClientId: string, apiKeyId: string, userId: string, meta: RequestMeta) {
    const key = await this.getOwnedKey(apiClientId, apiKeyId);
    if (key.revokedAt) {
      throw new BadRequestException("API key is already revoked");
    }

    const updated = await this.prisma.aPIKey.update({
      where: { id: apiKeyId },
      data: { revokedAt: new Date() },
      include: { scopes: true },
    });

    const client = await this.prisma.aPIClient.findUniqueOrThrow({ where: { id: apiClientId } });
    await this.auditService.record({
      action: "API_KEY_REVOKED",
      userId,
      organizationId: client.organizationId,
      applicationId: client.applicationId ?? undefined,
      metadata: { apiKeyId },
      ...meta,
    });

    return this.toSafeKey(updated);
  }

  /** Revokes the existing key and issues a replacement in one call, carrying over name/scopes/limits. */
  async rotate(
    apiClientId: string,
    apiKeyId: string,
    dto: RotateApiKeyDto,
    userId: string,
    meta: RequestMeta,
  ) {
    const existing = await this.getOwnedKey(apiClientId, apiKeyId);
    const now = new Date();

    await this.prisma.aPIKey.update({
      where: { id: apiKeyId },
      data: { revokedAt: existing.revokedAt ?? now, rotatedAt: now },
    });

    const generated = generateApiKey(dto.environment ?? "live");
    const created = await this.prisma.aPIKey.create({
      data: {
        apiClientId,
        name: existing.name,
        keyPrefix: generated.keyPrefix,
        keyHash: generated.keyHash,
        lastFour: generated.lastFour,
        rateLimitPerMin: existing.rateLimitPerMin,
        expiresAt: existing.expiresAt,
        scopes: existing.scopes.length
          ? { create: existing.scopes.map((s) => ({ scope: s.scope })) }
          : undefined,
      },
      include: { scopes: true },
    });

    const client = await this.prisma.aPIClient.findUniqueOrThrow({ where: { id: apiClientId } });
    await this.auditService.record({
      action: "API_KEY_ROTATED",
      userId,
      organizationId: client.organizationId,
      applicationId: client.applicationId ?? undefined,
      metadata: { oldApiKeyId: apiKeyId, newApiKeyId: created.id },
      ...meta,
    });

    return { ...this.toSafeKey(created), plainText: generated.plainText };
  }

  async addScope(apiClientId: string, apiKeyId: string, scope: string) {
    await this.getOwnedKey(apiClientId, apiKeyId);
    return this.prisma.aPIKeyScope.upsert({
      where: { apiKeyId_scope: { apiKeyId, scope } },
      create: { apiKeyId, scope },
      update: {},
    });
  }

  async removeScope(apiClientId: string, apiKeyId: string, scope: string): Promise<void> {
    await this.getOwnedKey(apiClientId, apiKeyId);
    await this.prisma.aPIKeyScope.deleteMany({ where: { apiKeyId, scope } });
  }

  private async getOwnedKey(apiClientId: string, apiKeyId: string): Promise<ApiKeyWithScopes> {
    const key = await this.prisma.aPIKey.findUnique({
      where: { id: apiKeyId },
      include: { scopes: true },
    });
    if (!key || key.apiClientId !== apiClientId) {
      throw new NotFoundException("API key not found");
    }
    return key;
  }

  private toSafeKey(key: ApiKeyWithScopes) {
    const { keyHash: _keyHash, ...safe } = key;
    return safe;
  }
}
